### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by rohkud**

### CODE REVIEW

**Comment by rohkud** [comment]
@TrustinN

**Comment by TrustinN** [comment]
bruh

**Comment by TrustinN** [comment]
Sorry, but we cannot accept your merge at this moment. Please follow the guidelines for formatting a proper pull request. I will be closing this now.

**Comment by rohkud** [comment]
Thank you for your consideration. Could you link the guidelines for formatting a proper pull request?

**Comment by TrustinN** [comment]
Yes, here is a detailed list of things to keep in mind: https://trustinn.github.io/pr_guidelines

Although we are very open to pull requests (thanks for your input), there are many things that we do not want to break in the project. Things to keep in mind:

<ul>
      <li>Include proper documentation for your changes</li>
      <li>Make sure your styling adheres to the guidelines listed above</li>
      <li>Add unit tests so we can see it works properly</li>
      <li>DO NOT import modules outside of current project dependencies</li>
      <li>Ensure your pull request is up-to-date and merge any conflicts from the main branch</li>
</ul>

You should also add a description for your pull request if you want a higher chance for it to be accepted. Here is an example:

<h3>Description</h3>
<p>
Provide a detailed description of the changes made in this pull request. Explain the purpose and context of the changes, any relevant background information, and how it addresses the issue or feature request.
</p>

<h3>Related Issues</h3>
<p>Link to any related issues (e.g., Fixes #1, Related to #456). Also include any output from log files that you have from the issue, and the stack trace output in a formatted code block</p>


<h3>Changes Made</h3>
List the main changes or additions.
<ul>
      <li>Use bullet points for clarity.</li>
      <li><code>Code changed + documentation</code></li>
</ul>

<h3>How to Test</h3>
Provide steps for testing the changes.
Include any specific configurations or dependencies needed.

Screenshots (if applicable)
Add screenshots to illustrate the changes, especially for UI modifications.

<h3>Checklist</h3>
<ul>
      <li>Code is well-commented </li>
      <li>Tests have been added/updated</li>
      <li>Documentation has been updated</li>
      <li>Changes have been tested in relevant environments</li>
</ul>

<h3>Additional Notes</h3>
<p>Any other information that reviewers should know.</p>

**Comment by rohkud** [comment]
Sounds good! By the way, I think the link you included is incorrect, as it takes me to an error page. I will keep the rest of the information in mind. Do you have any potential issues with the current state of the repo that could potentially need some pull requests?

**Comment by TrustinN** [comment]
<pre>
⎛ ⁔   ⁔ ⎞    No
⎝👁️👄👁️⎠
⎛  ⧓    ⎞</pre>

**Comment by rohkud** [comment]
#2

**Pull request closed without merging**
